name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Start local staging environment
      run: python ops/staging/run_local_staging.py --action start &
      
    - name: Wait for environment initialization
      run: sleep 20
        
    - name: Run pytest
      run: pytest -q --disable-warnings
      
    - name: Run smoke tests
      run: python ops/staging/smoke_test.py --wait 60
      
    - name: Stop local staging environment
      run: python ops/staging/run_local_staging.py --action stop
      
    - name: Upload test reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-reports
        path: |
          test_report.html
          test_report.json
          
  lint-pilot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: shellcheck
      run: shellcheck pilot_start.sh pilot_stop.sh

  soak-dry-run:
    runs-on: ubuntu-latest
    needs: tests
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run short soak test
      run: python ops/staging/soak_runner.py --hours 0.01
      
    - name: Validate soak test results
      run: python scripts/validate_soak.py reports/soak_report.json
      
    - name: Upload soak test report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: soak-test-report
        path: reports/soak_report.json