# Portfolio Diversified Configuration Template
# Designed for proper multi-ticker portfolio allocation

data:
  data_pool_dir: "data/pools"
  timeframe_folders:
    1minute: "1minute"
    5minute: "5minute" 
    15minute: "15minute"
    1hour: "1hour"
    1day: "1day"
  default_timeframe: "1minute"
  required_columns:
    - "timestamp"
    - "open"
    - "high"
    - "low"
    - "close"
    - "volume"
  date_format: "%Y-%m-%d"
  timezone: "Asia/Kolkata"

strategy:
  name: "mse"
  parameters: {}
  enabled: true
  description: "MSE strategy with portfolio diversification"
  risk_profile: "portfolio_diversified"
  initial_capital: 1000000.0

risk:
  # Portfolio-level risk controls
  enabled: true
  max_position_size: 0.15        # 15% max position (allows for diversification)
  max_daily_loss: 0.02           # 2% daily loss limit
  max_drawdown: 0.20             # 20% maximum drawdown
  max_concentration: 0.40        # 40% max concentration (allows multi-ticker)
  
  # Position controls
  stop_loss_pct: 0.05            # 5% stop loss
  take_profit_pct: 0.10          # 10% take profit
  position_timeout_minutes: 240   # 4 hours
  enable_stop_loss: true
  enable_take_profit: true
  enable_timeout: true

transaction:
  enabled: true
  model_type: "advanced"
  brokerage_rate: 0.0003
  fixed_cost: 0.0
  slippage_rate: 0.0001
  market_impact_factor: 0.1
  enable_market_impact: true

options:
  enabled: false

validation:
  enabled: true
  lookahead_bias_check: true
  survivorship_bias_check: true
  data_quality_check: true
  min_data_points: 50
  max_missing_data_pct: 0.05
  price_outlier_threshold: 3.0

optimization:
  enabled: false

output:
  save_trades: true
  save_metrics: true
  save_plots: true
  save_base_data: true
  output_dir: "outputs"
  trade_file_format: "csv"
  base_file_format: "csv"
  metrics_file_format: "json"
  plot_format: "png"

logging:
  level: "INFO"
  format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  file_enabled: true
  console_enabled: true
  log_dir: "logs"

# Portfolio execution settings
execution:
  parallel_processing: true
  max_workers: 3
